// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvwhhotclhakfyxbwxlk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2d2hob3RjbGhha2Z5eGJ3eGxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3Nzk0ODQsImV4cCI6MjA2OTM1NTQ4NH0._iDFkyQ2oSjpY5t2nH0E8p5FAz61402hNRDZ9I7gVAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});